# Generated by Django 4.0.3 on 2022-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='repassword',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
