# Generated by Django 4.0.3 on 2022-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_repassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='repassword',
            field=models.CharField(max_length=500),
        ),
    ]
